name: Testing Lab 1 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Maven
        run: mvn -B test

      - name: Run JUnit tests
        run: mvn test